from enum import StrEnum
from sqlalchemy import Enum,Column, Integer, String, Float, ForeignKey, DateTime, Boolean, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base

class Type(StrEnum):
    TAKE_AWAY = 'take away'
    EAT_IN = 'eat in'

class Categorie(Base):
    """
    Table 'categories'
    Ex: Pizzas, Panozzos, Boissons, Salades...
    """
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    nom = Column(String, unique=True, index=True, nullable=False)
    disponible = Column(Boolean, default=True)
    items = relationship("Item", back_populates="categorie", cascade="all, delete-orphan")


class Item(Base):
    """
    Table 'items' (les produits du menu)
    Ex: Margherita, Coca-Cola, Tiramisu...
    """
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True)
    nom = Column(String, index=True, nullable=False)
    options = Column(JSON, nullable=True)
    prix = Column(Float, nullable=False)
    disponible = Column(Boolean, default=True)
    quantite_en_stock = Column(Integer, nullable=True)
    last_modified = Column(DateTime, default=func.now(), onupdate=func.now())

    # Clé étrangère vers la table Categorie
    categorie_id = Column(Integer, ForeignKey("categories.id", ondelete="CASCADE"), nullable=False)

    # Relations
    categorie = relationship("Categorie", back_populates="items")


class Commande(Base):
    """
    Table 'commandes' (une commande globale pour une table)
    """
    __tablename__ = "commandes"

    id = Column(Integer, primary_key=True, index=True)
    table = Column(Integer, nullable=True)
    statut = Column(String, default="attente")  # "attente", "cuisine", "pret", "payee"
    date_creation = Column(DateTime(timezone=True), server_default=func.now())  #Automatic timestamp, generated by SQLite
    date_validation = Column(DateTime(timezone=True), server_default=func.now())
    items = relationship("CommandeItem", back_populates="commande", cascade="all, delete-orphan")
    type = Column(Enum(Type),default=Type.EAT_IN)


class CommandeItem(Base):
    """
    Table 'commande_items' (Lignes de commande d'association)
    Fait le lien entre une commande, un produit et sa quantité.
    """
    __tablename__ = "commande_items"

    id = Column(Integer, primary_key=True, index=True)
    commande_id = Column(Integer, ForeignKey("commandes.id", ondelete="CASCADE"), nullable=False)
    item_id = Column(Integer, ForeignKey("items.id", ondelete="RESTRICT"), nullable=False)  # RESTRICT empêche de supprimer un produit du menu s'il est présent dans une commande en cours
    option_selectionnee = Column(String, nullable=True)
    quantite = Column(Integer, default=1, nullable=False)
    commentaire = Column(String, nullable=True)  # Ex: "Sans oignons", "Sauce piquante à part"

    # Relations
    commande = relationship("Commande", back_populates="items")
    item = relationship("Item")